### ISSUE TITLE
Plan to do

### ISSUE THREAD

**Issue by xiaoluoboding** [xiaoluoboding/ghost-theme-kaldorei#1]
- [x] 主题基调定为小清新绿色
- [x] 文章样式色调为墨蓝色，参考 [[马克飞象]](http://maxiang.io)
- [x] 返回顶部
- [x] 代码高亮
- [x] 侧边栏 - 标签云
- [x] 侧边栏 - 文章目录
- [x] 侧边栏 - 站点信息
- [x] 侧边栏 - 作者信息
- [x] 文章栏 - 作者信息
- [x] 首页加载文章动画
- [x] 响应式设计
- [x] 归档功能
- [x] 图片暗箱效果
- [ ] 全局搜索

**Comment by bubbleatgit** [comment]
别的不想说，只想说博主的主题真漂亮！是目前见过的Ghost主题里面最漂亮的了。

**Comment by yotoobo** [comment]
博主可以给侧边栏目录增加跳转到正文对应位置吗？

**Comment by xiaoluoboding** [comment]
你好，现在应该是支持的。
发自网易邮箱大师

**Comment by yotoobo** [comment]
你好，找到原因了。我设置标题都是以 “### # 标题”这种形式，改为“### 标题”就都好了。非常感谢！！！

2017-07-14 11:36 GMT+08:00 Yunwei Xiao <notifications@github.com>:

**Comment by caryyu** [comment]
@xiaoluoboding 期待博主做 JekyII 的移植，我估计一定会火的爆掉的！！！ 😆

**Comment by Ice-Storm** [comment]
非常好用~加油
