### ISSUE TITLE
圖片點擊放大功能

### ISSUE THREAD

**Issue by lucyxss** [xiaoluoboding/ghost-theme-kaldorei#10]
我是kaldorei的fans，用了很久了。近期需要上傳一些大圖片，但是在頁面中顯示的不清楚。希望能加個點擊圖片放大的功能。另外希望留個微信打賞的二維碼。tank

**Comment by xiaoluoboding** [comment]
@lucyxss 感谢对kaldorei 的支持，请看下这篇文章，是否可以解决你的问题[Ghost博客使用fancybox的正确姿势](http://xlbd.me/ghostbo-ke-shi-yong-fancyboxde-zheng-que-zi-shi/)。

**Comment by lucyxss** [comment]
@xiaoluoboding 解決了，謝謝！
