### ISSUE TITLE
移动端有些信息要是能显示就好了. 

### ISSUE THREAD

**Issue by KISSMonX** [xiaoluoboding/ghost-theme-kaldorei#14]
如图: 我用手机和 pad 浏览的话, 并不显示.  
顺便多谢提供的这么好看的主题. 哈哈
![1](https://cloud.githubusercontent.com/assets/2876745/25752477/01754d4a-31eb-11e7-955f-658be309ee46.png)

**Comment by sxgxhk** [comment]
这个在Ghost0.7.4汉化版上是可以显示的（非PC端浏览），但在Ghost1.X版本上浏览就没有了，希望大神能够迭代修复，期待中
