### ISSUE TITLE
我不想再首页显示侧边栏，只想在post页面展示侧边栏，如何做？

### ISSUE THREAD

**Issue by istek** [xiaoluoboding/ghost-theme-kaldorei#16]

**Comment by xiaoluoboding** [comment]
博客设计为两栏式风格，所以设计初始没有考虑首页单栏的情况。所以不能简单的配置达到目的。

你需要改动`index.hbs`这个文件，把`{{> "sidebar"}}`去掉。但是左侧文章栏宽度会不变，没有响应式。

这时你需要改动`loop.hbs`文件

把
```html
<div id="content" class="content col-sm-12 col-md-8 col-lg-8">
```

改为

```html
<div id="content" class="content col-sm-12 col-md-12 col-lg-12">
```

另外还需要设置文章的宽度，改动`screen.css`。这个你可以自己尝试调试。
