### ISSUE TITLE
博客右上角的blog-title以及用户的头像的链接怎么改呢

### ISSUE THREAD

**Issue by arronf2e** [xiaoluoboding/ghost-theme-kaldorei#17]
我配了二级域名 ，但是链接仍是locahost:2368这样的，就报错了

**Comment by xiaoluoboding** [comment]
应该在后台配置下博客的链接。是不是你的博客后台**navigation**中首页还是设置的`localhost:2368`

**Comment by arronf2e** [comment]
http://ghost.omeme.me/   可以看一下， header中左边的网站大标题链接有问题，右边的三个倒是OK的，然后就是下面的用户头像

**Comment by xiaoluoboding** [comment]
@arronf2e 检查下`ghost`目录下的`config.js`文件，如果生产模式，应该填写你的域名[http://ghost.omeme.me](http://ghost.omeme.me)，有可能你这是作为开发模式启动的，开发模式默认就是`localhost:2368` 。

**Comment by arronf2e** [comment]
@xiaoluoboding 谢谢

**Comment by arronf2e** [comment]
@xiaoluoboding 可以啦
