### ISSUE TITLE
如果字数不够一页，并不能充满整个屏幕，下面会有白条

### ISSUE THREAD

**Issue by GeT1t** [xiaoluoboding/ghost-theme-kaldorei#18]
如果字数不够一页，并不能充满整个屏幕，下面会有白条，环境为：360极速浏览器及Chrome

**Comment by xiaoluoboding** [comment]
有没有截图或者链接，让我看下是什么样的问题。

**Comment by GeT1t** [comment]
http://www.get1t.cn/archives-post/

**Comment by GeT1t** [comment]
![image](https://user-images.githubusercontent.com/20207004/28601300-017a2e02-71ea-11e7-9c53-a55dc4489483.png)
