### ISSUE TITLE
创建独立页面时发现BUG一只

### ISSUE THREAD

**Issue by rrikmoe** [xiaoluoboding/ghost-theme-kaldorei#2]
新建博文时，勾选Turn this post into static page会导致新建的博文页面排版错乱

**Comment by xiaoluoboding** [comment]
@Tsezz Oh yeah,我忘记静态页面了。平时不怎么用。有时间优化下。

**Comment by xiaoluoboding** [comment]
@Tsezz 已经解决，请更新主题试下。

**Comment by rrikmoe** [comment]
谢谢，不过希望能在静态页面也加上disqus，比较方便的说
