### ISSUE TITLE
Support Ghost 1.0

### ISSUE THREAD

**Issue by S8Cloud** [xiaoluoboding/ghost-theme-kaldorei#20]
Ghost has released newest stable version 1.0.2 recently . I tested this theme using [gscan](https://gscan.ghost.org) and it shows that there's something to fix. Maybe it's a good idea to fix it.

![20170731_100806](https://user-images.githubusercontent.com/27051990/28760275-4ebec586-756b-11e7-917d-1b7a063aec0a.jpg)

**Comment by xiaoluoboding** [comment]
@wwwwwewe Thanks, I will upgrade Ghost 1.x recently, that time I will fixed this.
