### ISSUE TITLE
Fail to use fancybox 3

### ISSUE THREAD

**Issue by S8Cloud** [xiaoluoboding/ghost-theme-kaldorei#21]
I tried to upgrade fancybox from version 2 now in the theme to 3.2.1, I replaced the fancybox js and css in `/assets/plugins/` and upgraded the jquery version to 3. I also changed the js and css resources in `dafault.hbs` but I found that the fancy box plugin didn't work when I used it in the form `<a data-fancybox="gallery" href="big_1.jpg"><img src="small_1.jpg"></a>`.
I tried it in the same way and it successfully worked in `casper 2.0.5`.

Could you please tell me how to use fancybox 3, thanks.
http://fancyapps.com/fancybox/3/

**Comment by xiaoluoboding** [comment]
@S8Cloud I will test fancybox3 recently in Ghost 1.x. Thanks for tell me.

**Comment by xiaoluoboding** [comment]
@S8Cloud 
Kaldroei now support fancybox 3.1.25, you can update the latest repo.
Here is [how to use fancybox in ghost](http://xlbd.me/how-to-use-fancybox-in-ghost-blog/).
Have fun.
