### ISSUE TITLE
kaldorei发布文章的时间展示汉化

### ISSUE THREAD

**Issue by 1lg** [xiaoluoboding/ghost-theme-kaldorei#23]
作者您好，非常感谢您能将这么好的主题开源出来。我在使用时看到http://xlbd.me/kaldorei/ 里面说：

> About ghost helpers
> kaldorei 用两种方法实现了标签云，方法参见我的博客。
> kaldorei 优化了发布文章的时间展示，并汉化为中文，需要修改时间(date)助手，方法参见我的博客。

但是我在您的博客中并没有找到相应方法，能详细一点儿吗？谢谢

**Comment by 1lg** [comment]
希望作者有空了能看一下，谢谢

**Comment by xiaoluoboding** [comment]
抱歉回复晚了。参考[Ghost博客时间汉化方案](http://xlbd.me/ghost-date-i18n/)
