### ISSUE TITLE
Errors occurs when TOC contains special chars

### ISSUE THREAD

**Issue by xiongchengqing** [xiaoluoboding/ghost-theme-kaldorei#26]
it occurs errors when TOC contains special chars.  jQuery selector treats selector string which contains special chars (`*`,` -`, `^`, `?`, etc) as invalid syntax. When it comes to rich text headings like some SQL `select * from user` VS  `select * from "user"`, the TOC anchor jumping will fail.

This is my solution for the issue.

https://github.com/xiaoluoboding/ghost-theme-kaldorei/blob/6bd2e632daf25220e9ba58fc578f2fafa23a6596/assets/js/index.js#L82

change to below

```javascript
  var target = document.getElementById($(this).attr('href').split('#')[1]);
```

If  anyone have a better solution, pls update it.

<img width="1091" alt="wx20170918-160632 2x" src="https://user-images.githubusercontent.com/1636616/30533340-7715f50c-9c1e-11e7-9b87-78067bc44945.png">

**Comment by xiaoluoboding** [comment]
Thanks for fixed this bug.
