### ISSUE TITLE
我的站点文章目录没有显示呢

### ISSUE THREAD

**Issue by royburns** [xiaoluoboding/ghost-theme-kaldorei#27]
文章目录的展示有特别要注意的地方吗？我使用了heading

http://royburns.cn/

**Comment by xiaoluoboding** [comment]
请使用`markdown` 格式写作

**Comment by royburns** [comment]
就是markdown？不是ghost升级了改了某些标签？

**Comment by royburns** [comment]
我是用的markdown

**Comment by royburns** [comment]
http://royburns.cn/2018/01/02/yi-fen-jing-xin-tiao-xuan-de-zhong-wen-quantxiang-guan-zi-yuan-suo-yin/
