### ISSUE TITLE
样式没有显示出来

### ISSUE THREAD

**Issue by laolai** [xiaoluoboding/ghost-theme-kaldorei#32]
![image](https://user-images.githubusercontent.com/3068867/48321317-940c1680-e65c-11e8-9e93-b48b67464399.png)

上传主题激活后界面是上图这个样子的，使用的Ghost版本是2.4.0

**Comment by xiaoluoboding** [comment]
@laolai 我使用的Ghost版本也是2.4.0，有没有可能是对主题路径没有访问权限。
