### ISSUE TITLE
代码块行号

### ISSUE THREAD

**Issue by xmsec** [xiaoluoboding/ghost-theme-kaldorei#33]
代码块行号在原来的版本中是显示的，新版不显示了吗？请问要如何修改到原来的样式.. 尝试更改了失败了..

**Comment by xiaoluoboding** [comment]
额，是已经修改好了嘛。
代码行号，考虑到可以更换其他主题，目前没有跟随主题的变化而变化。都是暗色的。所以暂时去掉了。

**Comment by xmsec** [comment]
谢谢~最后改好了。是这样呀，突然感觉加不加行号都比较好看。
