### ISSUE TITLE
怎么替换微博之类的url

### ISSUE THREAD

**Issue by Ice-Storm** [xiaoluoboding/ghost-theme-kaldorei#34]
想替换一下微博，github图标指向的地址，在哪里可以呢？

**Comment by xiaoluoboding** [comment]
@Ice-Storm 不好意思，才看到。在这里修改。

https://github.com/xiaoluoboding/ghost-theme-kaldorei/blob/master/partials/social.hbs#L10

**Comment by Ice-Storm** [comment]
谢谢啦
