### ISSUE TITLE
无法显示中文

### ISSUE THREAD

**Issue by Fr33raNg3r** [xiaoluoboding/ghost-theme-kaldorei#40]
设置里面更改的语言选项为zh
重启了Ghost，刷新页面无效
![image](https://user-images.githubusercontent.com/15374658/59357978-54c2b700-8d5e-11e9-8af2-6b35bd6d8e55.png)
![image](https://user-images.githubusercontent.com/15374658/59357997-6310d300-8d5e-11e9-9431-c0a191f8ac63.png)
还是显示为英文
![image](https://user-images.githubusercontent.com/15374658/59358035-702dc200-8d5e-11e9-95c6-39bfaf7be882.png)
主题已更改
![image](https://user-images.githubusercontent.com/15374658/59358072-8471bf00-8d5e-11e9-82c4-ace98823bf35.png)
Ghost版本为最新的2.23

**Comment by xiaoluoboding** [comment]
有时间我测试下新版本的Ghost，在我的本地和线上跑的是没问题的。

**Comment by Fr33raNg3r** [comment]
看官网介绍还需要修改几个hbs文件，不知道理解正不正确
