### ISSUE TITLE
highlight.js 自定义主题School Book时，代码渲染样式错误

### ISSUE THREAD

**Issue by sionnx** [xiaoluoboding/ghost-theme-kaldorei#42]
我在code injection中添加
```

<!-- use school-book.css style -->
<link rel="stylesheet" type="text/css" href="/assets/plugins/highlight-latest/styles/school-book.css" />

```
正确的渲染效果如下：
![image](https://user-images.githubusercontent.com/24622986/61192605-2ed75c00-a6e8-11e9-8d4f-d8f72a70ea8d.png)

实际渲染效果如下：
![image](https://user-images.githubusercontent.com/24622986/61192617-457db300-a6e8-11e9-9921-29690af75b79.png)

**Comment by xiaoluoboding** [comment]
@lushans 等我试下

**Comment by sionnx** [comment]
好的

**Comment by xmsec** [comment]
其他的样式也有偏差，之前遇到这个问题没找到原因在哪

**Comment by xmsec** [comment]
刚刚测试了下，可能是新加入的样式不能完全覆盖默认的样式，两者渲染的 class 不一致，造成两个渲染文件都在使用状态。
我这边使用 solarized-light 感觉已经没问题了。之前函数的参数会使用默认渲染而成为白色。不确定有没有解决这个问题。
