### ISSUE TITLE
Ghost3.0版本取消v0.1API支持，ghost.url.api 失效

### ISSUE THREAD

**Issue by MRYOG** [xiaoluoboding/ghost-theme-kaldorei#43]
1 Ghost3.0版本取消v0.1API支持
2 /assets/js/guidang.js 文件中涉及的ghost.url.api 已经失效，需要删除或者升级
3 Themes using ghost.url.api() must upgrade to the Content API client library.

**Comment by xiaoluoboding** [comment]
@MRYOG 收到，最近正在对 ghost 3.x 做兼容，届时会发布新版本

**Comment by buzhidaocommon** [comment]
请问下。主题已经支持GHOST3.0了么？
