### ISSUE TITLE
您好 请问如何给highlight.js设置行号，我自己试了一下，css样式加载不对，不确定是否改的正常

### ISSUE THREAD

**Issue by onedaydayde** [xiaoluoboding/ghost-theme-kaldorei#44]
您好 请问如何给highlight.js设置行号，我自己试了一下，css样式加载不对，不确定是否改的正常
如果3.0版本中能增加一下这个功能就好了

**Comment by xiaoluoboding** [comment]
@onedaydayde 已实现[代码行号配置](https://github.com/xiaoluoboding/ghost-theme-kaldorei#-%E5%BC%80%E5%90%AF%E6%98%BE%E7%A4%BA%E4%BB%A3%E7%A0%81%E8%A1%8C%E5%8F%B7)
