### ISSUE TITLE
代码高亮有一定几率显示错误

### ISSUE THREAD

**Issue by ghost** [xiaoluoboding/ghost-theme-kaldorei#8]
代码高亮界面有几率会出现这样的情况
![image](https://cloud.githubusercontent.com/assets/20225995/22884818/c3572158-f231-11e6-9ee6-4ba71cb4a3c5.png)
浏览器 Chrome 58 Mac，截图界面来自 http://xlbd.me/kaldorei/

**Comment by xiaoluoboding** [comment]
您好，我在测试过程中未发现有这样的情况发生，应该是丢失了代码高亮的背景。
我在浏览器Chrome 55 Mac下是正常的。等我升级Chrome在测试下。

**Comment by ghost** [comment]
关于代码高亮还有一个显示问题，在 pc 端，代码框有滑动条控制滚动，一行显示一行代码，在 iOS 端，代码如果超过窗口宽度会自动换行，但是标注行号不会跳过换行过后的部分。就会导致代码行号标注错误的情况。

# 移动端显示（iOS 10，Safari & Chrome）
![image](https://cloud.githubusercontent.com/assets/20225995/23098885/83054abe-f694-11e6-8a15-73846a59bbc6.png)

# PC 端显示正常
![image](https://cloud.githubusercontent.com/assets/20225995/23098889/a53d6c10-f694-11e6-8496-9345ae4d20d1.png)

# Android 下显示正常（Anndroid 7.1.1 Chrome Dev ）
![image](https://cloud.githubusercontent.com/assets/20225995/23098943/dd445d52-f695-11e6-8439-37e67765436d.png)

> 截图来自 `http://xlbd.me/creating-github-pages-from-the-command-line/`

**Comment by xiaoluoboding** [comment]
问题收到。

**Comment by xiaoluoboding** [comment]
@jsczdcc 代码与行号在Safari和IOS环境下显示错位问题已修复。
